### ISSUE TITLE
 You renamed the ADO Plugin task, that is a breaking change!

### ISSUE THREAD

**Issue by landymore** [Checkmarx/ast-azure-plugin#321]
This commit: https://github.com/Checkmarx/ast-azure-plugin/commit/c4bad398dcc6264c08ca51033c87e16c89894b6b

broke our world, hundreds of pipelines using templates.

**Comment by landymore** [comment]
Please make sure you don't do this again without some advanced notice...

**Comment by pedrompflopes** [comment]
@landymore  We are rolling back the change, we will create a major release with this change.

**Comment by landymore** [comment]
We have already implemented a fix... if you push a new version that rolls the change back, we will be broken again...

**Comment by pedrompflopes** [comment]
It had an impact on other clients. We are trying to minimize the impact, we will create a major next week with the change.
